### ISSUE TITLE
Possible issues with AnaplanModels.sync_models and AnaplanModels.compatible_revisions

### ISSUE THREAD

**Issue by coversoncharlie** [hopfenspiel/PlanaPY#1]
Apologies if any of this is known or if I'm missing something- just spotted and thought I should share as a just in case.

Whenever attempting to run AnaplanModels.sync_models the error 'Error occurred: AnaplanModels.compatible_revisions() missing 1 required positional argument: 'workspace'' is received. Looking in the source code it seems as though the "SourceRevisionId" is missing the workspace argument in its use of compatible_revisions-
"sourceRevisionId": self.compatible_revisions( ## most recent compatible revision
                                        source_model = source_model, 
                                        target_model = target_model)['revisions'][0]['id']

rather than-
"sourceRevisionId": self.compatible_revisions( ## most recent compatible revision
                                        source_model = source_model, 
                                        target_model = target_model,
                                        workspace = workspace)['revisions'][0]['id']

Adding this argument removes the aforementioned error but presents the following-
Error occurred: 'revisions'

Seemingly because the dict item returned from compatible_revisions has no such key, in my case only returning the following-
{'meta': {'schema': 'https://api.anaplan.com/2/0/objects/revision'},
 'status': {'code': 200, 'message': 'Success'}}

With no key containing the latest compatible revision as the comment in the code would suggest is expected. Note that this was followed by a successful compare/sync of source_model -> target_model with a revision created by PlanaPY directly in Anaplan (outside of Python).

**Comment by coversoncharlie** [comment]
To be clear, the revision created via PlanaPY was done so prior to running the tests on sync_models to ensure a revision was available

**Comment by coversoncharlie** [comment]
Issue with the compatible revisions seems to be that the t_model_id is set to look for the source_model rather than the target_model, so the request is checking to see if there are any structural differences between a model and itself-    

        s_model_id = self.models[(self.models.name == source_model) 
                                            & (self.models.currentWorkspaceName == workspace)]['id'].iloc[0]
        t_model_id = self.models[(_**self.models.name == source_model**_) 
                                 & (self.models.currentWorkspaceName == workspace)]['id'].iloc[0]

**Comment by hopfenspiel** [comment]
thanks @coversoncharlie for bringing this up. Checking it out, should have it cleaned up soon.

**Comment by hopfenspiel** [comment]
Alright @coversoncharlie should be good to go! Let me know if you're still having issues.
